// Подписи интерфейса на всех языках сайта. Тексты страниц переводятся отдельно (content/i18n).
import type { Lang } from "./i18n";

const ru = {
  skip: "К содержанию",
  home: "Главная",
  toHome: "Car City, на главную",
  menu: "Меню",
  mainMenu: "Основное меню",
  language: "Язык",
  lead: "Оставить заявку",
  call: "Позвонить",
  request: "Заявка",
  quick: "Быстрая связь",
  nav: { fleet: "Автопарк", vykup: "Выкуп", usloviya: "Условия", onas: "О нас", reviews: "Отзывы", contact: "Контакты", news: "Новости" },
  footer: {
    rent: "Аренда", buy: "Выкуп", company: "Компания", offices: "Офисы", metro: "м.",
    privacy: "Политика конфиденциальности", sitemap: "Карта сайта", group: "Входит в группу Элит Кар",
    rentIp: "Аренда такси для ИП", rto: "Аренда с правом выкупа", buyEkonom: "Выкуп эконом", buyKomfort: "Выкуп комфорт", buyKomfortPlus: "Выкуп комфорт+",
  },
  cls: { ekonom: "Эконом", komfort: "Комфорт", "komfort-plyus": "Комфорт+", komfortplus: "Комфорт+", biznes: "Бизнес", gruzovoy: "Грузовой", dostavka: "Доставка" } as Record<string, string>,
  crumbs: "Хлебные крошки",
  cars: "Автомобили",
  classes: "Классы",
  faq: "Частые вопросы",
  mode: "Формат",
  rent: "Аренда",
  buy: "Выкуп",
  from: "от",
  perDay: "₽/сутки",
  rentCta: "Арендовать",
  buyCta: "Выкупить",
  more: "Подробнее",
  news: "Новости",
  readMin: "мин чтения",
  toc: "Содержание",
  articles: "Статьи",
  reviewsAll: "Все",
  reviewsLabel: "Отзывы водителей",
  source: "Площадка",
  stars: "Оценка 5 из 5",
  sitemap: "Карта сайта",
  sections: "Разделы",
  finalEyebrow: "Заявка",
  finalTitle: "Дарим 1-ый день бесплатно!",
  finalText: "Оставьте заявку, и наши менеджеры проконсультируют вас по всем вопросам!",
  finalButton: "Получить расчёт",
  notTranslated: "Эта страница пока доступна только на русском.",
};

export type Ui = typeof ru;

const en: Ui = {
  skip: "Skip to content",
  home: "Home",
  toHome: "Car City, home",
  menu: "Menu",
  mainMenu: "Main menu",
  language: "Language",
  lead: "Leave a request",
  call: "Call",
  request: "Request",
  quick: "Quick contact",
  nav: { fleet: "Fleet", vykup: "Rent-to-own", usloviya: "Terms", onas: "About", reviews: "Reviews", contact: "Contacts", news: "News" },
  footer: {
    rent: "Rent", buy: "Rent-to-own", company: "Company", offices: "Offices", metro: "Metro",
    privacy: "Privacy policy", sitemap: "Sitemap", group: "Part of the Elit Car group",
    rentIp: "Taxi rental for sole proprietors", rto: "Rent-to-own", buyEkonom: "Rent-to-own Economy", buyKomfort: "Rent-to-own Comfort", buyKomfortPlus: "Rent-to-own Comfort+",
  },
  cls: { ekonom: "Economy", komfort: "Comfort", "komfort-plyus": "Comfort+", komfortplus: "Comfort+", biznes: "Business", gruzovoy: "Cargo", dostavka: "Delivery" },
  crumbs: "Breadcrumbs",
  cars: "Cars",
  classes: "Classes",
  faq: "Frequently asked questions",
  mode: "Format",
  rent: "Rent",
  buy: "Rent-to-own",
  from: "from",
  perDay: "₽/day",
  rentCta: "Rent",
  buyCta: "Rent-to-own",
  more: "Details",
  news: "News",
  readMin: "min read",
  toc: "Contents",
  articles: "Articles",
  reviewsAll: "All",
  reviewsLabel: "Driver reviews",
  source: "Source",
  stars: "Rated 5 out of 5",
  sitemap: "Sitemap",
  sections: "Sections",
  finalEyebrow: "Request",
  finalTitle: "Your first day is free!",
  finalText: "Leave a request and our managers will answer all your questions!",
  finalButton: "Get a quote",
  notTranslated: "This page is only available in Russian for now.",
};

const ky: Ui = {
  skip: "Мазмунга өтүү",
  home: "Башкы бет",
  toHome: "Car City, башкы бетке",
  menu: "Меню",
  mainMenu: "Негизги меню",
  language: "Тил",
  lead: "Өтүнмө калтыруу",
  call: "Чалуу",
  request: "Өтүнмө",
  quick: "Тез байланыш",
  nav: { fleet: "Автопарк", vykup: "Сатып алуу", usloviya: "Шарттар", onas: "Биз жөнүндө", reviews: "Пикирлер", contact: "Байланыш", news: "Жаңылыктар" },
  footer: {
    rent: "Ижара", buy: "Сатып алуу", company: "Компания", offices: "Кеңселер", metro: "м.",
    privacy: "Купуялык саясаты", sitemap: "Сайттын картасы", group: "Элит Кар тобуна кирет",
    rentIp: "ЖИ үчүн такси ижарасы", rto: "Сатып алуу укугу менен ижара", buyEkonom: "Эконом сатып алуу", buyKomfort: "Комфорт сатып алуу", buyKomfortPlus: "Комфорт+ сатып алуу",
  },
  cls: { ekonom: "Эконом", komfort: "Комфорт", "komfort-plyus": "Комфорт+", komfortplus: "Комфорт+", biznes: "Бизнес", gruzovoy: "Жүк ташуучу", dostavka: "Жеткирүү" },
  crumbs: "Навигация",
  cars: "Унаалар",
  classes: "Класстар",
  faq: "Көп берилүүчү суроолор",
  mode: "Формат",
  rent: "Ижара",
  buy: "Сатып алуу",
  from: "",
  perDay: "₽/суткасынан",
  rentCta: "Ижарага алуу",
  buyCta: "Сатып алуу",
  more: "Толугураак",
  news: "Жаңылыктар",
  readMin: "мүн окуу",
  toc: "Мазмуну",
  articles: "Макалалар",
  reviewsAll: "Баары",
  reviewsLabel: "Айдоочулардын пикирлери",
  source: "Аянтча",
  stars: "5тен 5 баа",
  sitemap: "Сайттын картасы",
  sections: "Бөлүмдөр",
  finalEyebrow: "Өтүнмө",
  finalTitle: "Биринчи күн бекер!",
  finalText: "Өтүнмө калтырыңыз, менеджерлерибиз бардык суроолор боюнча кеңеш беришет!",
  finalButton: "Эсеп алуу",
  notTranslated: "Бул бет азырынча орусча гана.",
};

const kk: Ui = {
  skip: "Мазмұнға өту",
  home: "Басты бет",
  toHome: "Car City, басты бетке",
  menu: "Мәзір",
  mainMenu: "Негізгі мәзір",
  language: "Тіл",
  lead: "Өтінім қалдыру",
  call: "Қоңырау шалу",
  request: "Өтінім",
  quick: "Жылдам байланыс",
  nav: { fleet: "Автопарк", vykup: "Сатып алу", usloviya: "Шарттар", onas: "Біз туралы", reviews: "Пікірлер", contact: "Байланыс", news: "Жаңалықтар" },
  footer: {
    rent: "Жалға алу", buy: "Сатып алу", company: "Компания", offices: "Кеңселер", metro: "м.",
    privacy: "Құпиялылық саясаты", sitemap: "Сайт картасы", group: "Элит Кар тобына кіреді",
    rentIp: "ЖК үшін такси жалға алу", rto: "Сатып алу құқығымен жалға алу", buyEkonom: "Эконом сатып алу", buyKomfort: "Комфорт сатып алу", buyKomfortPlus: "Комфорт+ сатып алу",
  },
  cls: { ekonom: "Эконом", komfort: "Комфорт", "komfort-plyus": "Комфорт+", komfortplus: "Комфорт+", biznes: "Бизнес", gruzovoy: "Жүк", dostavka: "Жеткізу" },
  crumbs: "Навигация",
  cars: "Көліктер",
  classes: "Сыныптар",
  faq: "Жиі қойылатын сұрақтар",
  mode: "Формат",
  rent: "Жалға алу",
  buy: "Сатып алу",
  from: "",
  perDay: "₽/тәулігіне бастап",
  rentCta: "Жалға алу",
  buyCta: "Сатып алу",
  more: "Толығырақ",
  news: "Жаңалықтар",
  readMin: "мин оқу",
  toc: "Мазмұны",
  articles: "Мақалалар",
  reviewsAll: "Барлығы",
  reviewsLabel: "Жүргізушілер пікірлері",
  source: "Алаң",
  stars: "5-тен 5 баға",
  sitemap: "Сайт картасы",
  sections: "Бөлімдер",
  finalEyebrow: "Өтінім",
  finalTitle: "Бірінші күн тегін!",
  finalText: "Өтінім қалдырыңыз, менеджерлеріміз барлық сұрақтар бойынша кеңес береді!",
  finalButton: "Есеп алу",
  notTranslated: "Бұл бет әзірге тек орыс тілінде.",
};

const uz: Ui = {
  skip: "Mazmunga oʻtish",
  home: "Bosh sahifa",
  toHome: "Car City, bosh sahifaga",
  menu: "Menyu",
  mainMenu: "Asosiy menyu",
  language: "Til",
  lead: "Ariza qoldirish",
  call: "Qoʻngʻiroq qilish",
  request: "Ariza",
  quick: "Tezkor aloqa",
  nav: { fleet: "Avtopark", vykup: "Sotib olish", usloviya: "Shartlar", onas: "Biz haqimizda", reviews: "Sharhlar", contact: "Aloqa", news: "Yangiliklar" },
  footer: {
    rent: "Ijara", buy: "Sotib olish", company: "Kompaniya", offices: "Ofislar", metro: "m.",
    privacy: "Maxfiylik siyosati", sitemap: "Sayt xaritasi", group: "Elit Kar guruhiga kiradi",
    rentIp: "YaTT uchun taksi ijarasi", rto: "Sotib olish huquqi bilan ijara", buyEkonom: "Ekonom sotib olish", buyKomfort: "Komfort sotib olish", buyKomfortPlus: "Komfort+ sotib olish",
  },
  cls: { ekonom: "Ekonom", komfort: "Komfort", "komfort-plyus": "Komfort+", komfortplus: "Komfort+", biznes: "Biznes", gruzovoy: "Yuk", dostavka: "Yetkazib berish" },
  crumbs: "Navigatsiya",
  cars: "Avtomobillar",
  classes: "Sinflar",
  faq: "Koʻp beriladigan savollar",
  mode: "Format",
  rent: "Ijara",
  buy: "Sotib olish",
  from: "",
  perDay: "₽/kundan",
  rentCta: "Ijaraga olish",
  buyCta: "Sotib olish",
  more: "Batafsil",
  news: "Yangiliklar",
  readMin: "daq oʻqish",
  toc: "Mundarija",
  articles: "Maqolalar",
  reviewsAll: "Hammasi",
  reviewsLabel: "Haydovchilar sharhlari",
  source: "Manba",
  stars: "5 dan 5 baho",
  sitemap: "Sayt xaritasi",
  sections: "Boʻlimlar",
  finalEyebrow: "Ariza",
  finalTitle: "Birinchi kun bepul!",
  finalText: "Ariza qoldiring, menejerlarimiz barcha savollar boʻyicha maslahat beradi!",
  finalButton: "Hisob-kitob olish",
  notTranslated: "Bu sahifa hozircha faqat rus tilida.",
};

export const UI: Record<Lang, Ui> = { ru, en, ky, kk, uz };
export const ui = (lang: Lang) => UI[lang] ?? ru;
